use_frameworks!

target 'KVMapping_Example' do
  pod 'KVMapping', :path => '../'

  target 'KVMapping_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
