use_frameworks!

target 'KVMapper_Example' do
  pod 'KVMapper', :path => '../'

  target 'KVMapper_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
